name: melly
channels:
  - conda-forge
dependencies:
  - scipy
  - imageio
  - pandas
  - matplotlib
  - seaborn
  - dask-core
  - dask-image
  - scikit-image
  - zarr
  - numcodecs
  - jupyterlab
  - ipywidgets
  - dask-labextension
  - matplotlib-scalebar
  - openpyxl
  - tqdm
